# SPDX-FileCopyrightText: 2025 Digg - Agency for Digital Government
#
# SPDX-License-Identifier: CC0-1.0

# Release Workflow for cose-lib
# Uses the unified release orchestrator with Maven library publisher
---
name: Release Workflow

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"              # Stable: v1.0.0
      - "v[0-9]+.[0-9]+.[0-9]+-SNAPSHOT*"    # Snapshot: v1.0.0-SNAPSHOT

permissions:
  contents: read  # Best Security practice. Jobs only get read as base, and then permissions are added as needed

jobs:
  release:
    uses: diggsweden/.github/.github/workflows/release-orchestrator.yml@feat/ci-refactor
    permissions:
      contents: write   # Create GitHub releases and tags
      packages: write   # Publish to GitHub Packages (backup)
      id-token: write   # Generate OIDC token for Maven Central
      issues: write     # Close milestone and update issues with release info
    secrets: inherit  # Use org-level MAVEN_CENTRAL credentials and GPG keys
    with:
      # Project configuration
      projectType: maven  # Build system type (determines version file location)
      
      # Publishers and tools
      artifactPublisher: maven-lib-mavencentral       # Publish library to Maven Central
      artifact.jreleaserenabled: true                 # JReleaser plugin configured in pom.xml
      artifact.settingspath: ".mvn/settings.xml"      # Contains Maven Central server config
      
      changelogCreator: git-cliff  # Generate changelog from commit messages